// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import ()

type User struct {
	ID          int64    `json:"id"`
	ChatID      string   `json:"chatId"`
	Password    string   `json:"password"`
	UserPrompts []string `json:"userPrompts"`
}
